import type { GraphLink, GraphNode } from '$lib/types/graph';

export const nodes: GraphNode[] = [
	{ id: 'auth_doc', type: 'document', cluster: 'auth', label: 'Auth Docs' },
	{ id: 'login', type: 'section', cluster: 'auth', label: 'Login Flow' },
	{ id: 'jwt', type: 'entity', cluster: 'auth', label: 'JWT' },
	{ id: 'oauth', type: 'entity', cluster: 'auth', label: 'OAuth2' },
	{ id: 'api', type: 'entity', cluster: 'shared', label: 'API' },
	{ id: 'security', type: 'entity', cluster: 'shared', label: 'Security' },
	{ id: 'pay_doc', type: 'document', cluster: 'payments', label: 'Payments Docs' },
	{ id: 'checkout', type: 'section', cluster: 'payments', label: 'Checkout' },
	{ id: 'stripe', type: 'entity', cluster: 'payments', label: 'Stripe API' },
	{ id: 'webhook', type: 'entity', cluster: 'payments', label: 'Webhook' },
	{ id: 'analytics_doc', type: 'document', cluster: 'analytics', label: 'Analytics Docs' },
	{ id: 'tracking', type: 'section', cluster: 'analytics', label: 'Event Tracking' },
	{ id: 'ga', type: 'entity', cluster: 'analytics', label: 'Google Analytics' },
	{ id: 'bigquery', type: 'entity', cluster: 'analytics', label: 'BigQuery' },
	{ id: 'docs_home', type: 'document', cluster: 'docs', label: 'Docs Home' },
	{ id: 'getting_started', type: 'section', cluster: 'docs', label: 'Getting Started' },
	{ id: 'infra_doc', type: 'document', cluster: 'infra', label: 'Infra Docs' },
	{ id: 'deploy', type: 'section', cluster: 'infra', label: 'Deployments' },
	{ id: 'k8s', type: 'entity', cluster: 'infra', label: 'Kubernetes' },
	{ id: 'ci_doc', type: 'document', cluster: 'ci', label: 'CI Docs' },
	{ id: 'pipelines', type: 'section', cluster: 'ci', label: 'Pipelines' },
	{ id: 'github_actions', type: 'entity', cluster: 'ci', label: 'GitHub Actions' },
];

export const links: GraphLink[] = [
	{ source: 'auth_doc', target: 'login' },
	{ source: 'login', target: 'jwt' },
	{ source: 'login', target: 'oauth' },
	{ source: 'jwt', target: 'security' },
	{ source: 'pay_doc', target: 'checkout' },
	{ source: 'checkout', target: 'stripe' },
	{ source: 'stripe', target: 'webhook' },
	{ source: 'stripe', target: 'api' },
	{ source: 'oauth', target: 'api' },
	{ source: 'webhook', target: 'security' },
	{ source: 'analytics_doc', target: 'tracking' },
	{ source: 'tracking', target: 'ga' },
	{ source: 'ga', target: 'bigquery' },
	{ source: 'docs_home', target: 'getting_started' },
	{ source: 'getting_started', target: 'auth_doc' },
	{ source: 'getting_started', target: 'pay_doc' },
	{ source: 'infra_doc', target: 'deploy' },
	{ source: 'deploy', target: 'k8s' },
	{ source: 'deploy', target: 'stripe' },
	{ source: 'ci_doc', target: 'pipelines' },
	{ source: 'pipelines', target: 'github_actions' },
	{ source: 'github_actions', target: 'deploy' },
	{ source: 'github_actions', target: 'security' },
];
